language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx
  - windows
cache: cargo
before_install:
  - sudo apt-get update
  - sudo apt-get install -y glslang-tools
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
  script:
  - chmod +x spirvtest && ./spirvtest
  - cargo test --verbose --features opengl
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cargo test --verbose --features vulkan --release; fi
