language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx
  - windows
cache: cargo
before_install:
  - |
    mkdir glslang
    cd glslang
    wget https://github.com/KhronosGroup/glslang/releases/download/master-tot/glslang-master-linux-Release.zip
    unzip -u -q glslang-master-linux-Release.zip
    cd ..
    export PATH=${TRAVIS_BUILD_DIR}/glslang/bin:$PATH
    glslangValidator --version

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
script:
  - chmod +x spirvtest && ./spirvtest
  - cargo test --verbose --features opengl
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cargo test --verbose --features vulkan --release; fi
