[package]
name = "coffee"
version = "0.0.0"
authors = ["Héctor Ramón Jiménez <hector0193@gmail.com>"]
edition = "2018"
description = "An opinionated 2D game engine"
license = "MIT"

[dependencies]
winit = "0.19"
gfx = "0.18"
gfx_core = "0.9"
glutin = "0.20"
gfx_device_gl = "0.16"
gfx_window_glutin = "0.30"
image = "0.21"
nalgebra = "0.18"
gfx_glyph = "0.14"
log = "0.4"
